config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'account(/:auth_token)/profile' => 'account#profile'

  get '/auth/failure', to: 'authentications#failure'
  post '/auth/ldap/callback', to: 'authentications#create'
  get '/auth/ldap', to: 'authentications#passthru'

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login' }, path: ''


  # Resources
  resources :users
  resources :data_dictionary do
    post 'data_attribute_form', :on => :collection
  end
  resources :data_types

  get 'documentations/latest/:type/:id', to: "documentations#latest", as: :latest_documentation
  get 'sources/latest/:type/:id', to: "sources#latest", as: :latest_source

  resources :documentations
  resources :event_dictionary

  post 'events/report', to: "events#report", as: :report

  get 'events/report', to: "events#report"
  get 'events/:name/report/subject/:subject_code/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject/:subject_code', to: "events#report"
  get 'events/:name/report/subject_group/:subject_group_name/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject_group/:subject_group_name', to: "events#report"
  get 'events/:name/report/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report', to: "events#report"

  resources :events do
    get ':name', action: :new, on: :new
  end
  resources :sources
  resources :source_types
  resources :subject_groups
  resources :subjects do
    collection do
      post 'create_list'
      get 'new_list'
    end
  end


  get 'tasci_merger', to: 'tools#tasci_merger', as: :tasci_merger
  post 'tasci_merger', to: 'tools#tasci_merger', as: :merge_tasci

  root 'documentations#index'
end

app/models/data_type.rb
class DataType < ActiveRecord::Base
  ##
  # Associations
  has_many :data_dictionary

  ##
  # Attributes
  # attr_accessible :length, :multiple, :name, :range, :storage, :values

  ##
  # Callbacks

  ##
  # Concerns
  include Loggable, Deletable, Indexable

  ##
  # Scopes
  scope :search, lambda { |term| search_scope([:name], term) }

  ##
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  ##
  # Class Methods

  ##
  # Instance Methods

  private
end

app/models/event_dictionary.rb
class EventDictionary < ActiveRecord::Base
  ##
  # Associations
  has_many :event_tags, :through => :event_dictionary_event_tags
  has_many :event_dictionary_event_tags
  has_many :data_dictionary, :through => :event_dictionary_data_fields
  has_many :event_dictionary_data_fields
  has_many :events, :foreign_key => :name, :primary_key => :name
  belongs_to :paired_event_dictionary_i, class_name: "EventDictionary", foreign_key: "paired_id"
  has_one :paired_event_dictionary, class_name: "EventDictionary", foreign_key: "paired_id", autosave: true

  ##
  # Attributes
  #attr_accessible :description, :name, :data_dictionary_ids, :event_tag_ids

  ##
  # Callbacks

  ##
  # Concerns
  include Loggable, Indexable, Deletable

  ##
  # Database Settings

  ##
  # Scopes
  scope :search, lambda { |term| search_scope([:name, :description], term) }

  ##
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  ##
  # Class Methods

  ##
  # Instance Methods

  def event_data_query_sql(attrs = {})
    paired = attrs[:ignore_paired] ? nil : paired_event_dictionary
    event_records = [self, paired].compact
    data_records = event_records.map(&:data_dictionary).flatten.uniq

    data_query = []
    data_titles = []

    query = "select s.id subject_id, s.subject_code subject_code"
    
    if event_records.length > 1
      event_records.each_with_index do |er, j|
        i = j + 1
        query += %(, max( decode(e.name, '#{er.name}', e.id)) #{i.en.ordinate}_event_id,
          max( decode(e.name, '#{er.name}', e.name)) #{i.en.ordinate}_event_name,
          max( decode(e.name, '#{er.name}', labtime_hour)) #{i.en.ordinate}_labtime_hour,
          max( decode(e.name, '#{er.name}', labtime_min)) #{i.en.ordinate}_labtime_min,
          max( decode(e.name, '#{er.name}', labtime_sec)) #{i.en.ordinate}_labtime_sec,
          max( decode(e.name, '#{er.name}', labtime_year)) #{i.en.ordinate}_labtime_year,
          max( decode(e.name, '#{er.name}', labtime_decimal(e.labtime_hour, e.labtime_min, e.labtime_sec))) #{i.en.ordinate}_decimal_labtime,
          max( decode(e.name, '#{er.name}', realtime)) #{i.en.ordinate}_realtime)
      end
    else
      query += ", e.id event_id, max(e.name) event_name, max(e.labtime_hour) labtime_hour, max(e.labtime_min) labtime_min, max(e.labtime_sec) labtime_sec, max(e.labtime_year) labtime_year, max(labtime_decimal(e.labtime_hour, e.labtime_min, e.labtime_sec)) decimal_labtime, max(e.realtime) realtime"
    end
    
    data_records.each do |dr|
      q = "max( decode( d.title, '#{dr.title}', #{dr.data_type.storage})) #{dr.title.truncate(30, omission: '')}"
      data_titles << dr.title unless data_titles.include? dr.title
      data_query << q unless data_query.include? q
    end

    unless data_query.empty?
      query += (", " + data_query.join(",\n"))
    end

    query += %(
      from events e
        join subjects s on s.id = e.subject_id
        left join data d on d.event_id = e.id
        left join data_values dv on d.id = dv.datum_id
        join subjects_subject_groups ssg on ssg.subject_id = s.id
        join subject_groups sg on sg.id = ssg.subject_group_id\n
    )

    query += %(where (#{event_records.map{|er| "e.name = '#{er.name}'"}.join(' or ')}))
    query += %( and sg.name = '#{attrs[:subject_group_name]}') if attrs[:subject_group_name]
    query += %( and s.subject_code = '#{attrs[:subject_code]}') if attrs[:subject_code]

    query += %(\n
      group by s.id, s.subject_code, #{event_records.length > 1 ? "e.group_label" : "e.id"}
      order by s.subject_code, #{"first_" if event_records.length > 1}decimal_labtime
    )

    query.strip.gsub(/\s+/, ' ')
  end

  private
end

app/controllers/event_dictionary_controller.rb
class EventDictionaryController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /event_dictionary
  # GET /event_dictionary.json
  def index
    event_dictionary_scope = EventDictionary.current
    @event_dictionary = event_dictionary_scope.search_by_terms(parse_search_terms(params[:search])).set_order(params[:order], "name asc").page_per(params) #.page(params[:page] ? params[:page] : 1).per(params[:per_page] == "all" ? nil : params[:per_page])
  end

  # GET /event_dictionary/1
  # GET /event_dictionary/1.json
  def show
  end

  # GET /event_dictionary/new
  def new
    @event_dictionary = EventDictionary.new
  end

  # GET /event_dictionary/1/edit
  def edit
  end

  # POST /event_dictionary
  # POST /event_dictionary.json
  def create
    @event_dictionary = EventDictionary.logged_new(event_dictionary_params, current_user)

    respond_to do |format|
      if @event_dictionary.save
        format.html { redirect_to @event_dictionary, notice: 'EventDictionary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event_dictionary }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_dictionary/1
  # PATCH/PUT /event_dictionary/1.json
  def update
    respond_to do |format|
      if @event_dictionary.logged_update(event_dictionary_params)
        format.html { redirect_to @event_dictionary, notice: 'EventDictionary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_dictionary/1
  # DELETE /event_dictionary/1.json
  def destroy
    @event_dictionary.destroy
    respond_to do |format|
      format.html { redirect_to event_dictionary_index_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event_dictionary
    @event_dictionary = EventDictionary.current.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_dictionary_params
    params.require(:event_dictionary).permit(:name, :description, :paired_id, data_dictionary_ids: [], event_tag_ids: [])
  end
end

app/views/event_dictionary/_event_dictionary.html.erb
<p class='text-info object-info'><%= page_entries_info @event_dictionary %></p>
<table class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th><%= sort_field_helper(params[:order], 'name', 'Name') %></th>
      <th>Data Records</th>
      <th><%= sort_field_helper(params[:order], 'description', 'Description') %></th>
      <th><%= sort_field_helper(params[:order], 'created_at', 'Created') %></th>
      <th><%= sort_field_helper(params[:order], 'updated_at', 'Updated') %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <% @event_dictionary.each do |event_dictionary| %>
    <tr>
      <td><%= link_to event_dictionary.name, event_dictionary %></td>
      <td><%= event_dictionary.data_dictionary.map(&:title).length %></td>
      <td><%= event_dictionary.description %></td>
      <td><%= simple_date(event_dictionary.created_at) %></td>
      <td><%= simple_date(event_dictionary.updated_at) %></td>
      <td>
        <%= render partial: 'layouts/index_actions', locals: {object: event_dictionary, edit_path: edit_event_dictionary_path(event_dictionary) } %>
      </td>
    </tr>
  <% end %>
</table>

<div class="center"><%= paginate @event_dictionary %></div>

app/views/event_dictionary/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= form_for @event_dictionary, html: { role: 'form' } do |f| %>
<%= display_errors @event_dictionary %>
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :name, nil, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, nil, class: 'control-label' %>
      <%= f.text_area :description, rows: 7, class: 'form-control md' %>
    </div>

  </div>
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :paired_id, "Paired Event Record", class: 'control-label' %><br/>
      <%= f.select :paired_id, [[nil, nil]] + EventDictionary.current.collect{|s| [s.name, s.id]}, {}, {rel: 'chosen', class: 'form-control', data: {placeholder: "Choose paired record if applicable..."}} %>
    </div>
    <div class="form-group">
      <%= f.label :event_tag_ids, "Event Tags", class: 'control-label' %><br/>
      <%= f.collection_select :event_tag_ids, EventTag.current.order(:name), :id, :name, {}, {multiple:true, rel: 'chosen', class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.label :data_dictionary_ids, "Data Records", class: 'control-label' %><br/>
      <%= f.collection_select :data_dictionary_ids, DataDictionary.current.order(:title), :id, :title, {}, {multiple:true, rel: 'chosen', class: 'form-control', data: {placeholder: "Choose associated Data Dictionary variables..."}} %>
    </div>
  </div>
</div>


<div class="form-actions">
  <%= f.submit "Create Event Dictionary", class: 'btn btn-primary' %>
  <%= cancel %>
</div>
<% end %>

app/views/event_dictionary/edit.html.erb
<% @title = "Edit Event Dictionary: #{@event_dictionary.name}" %>

<%= render 'form' %>

app/views/event_dictionary/index.html.erb
<% @title = 'Event Dictionaries' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Event Dictionary", new_event_dictionary_path, class: 'btn btn-mini btn-primary' %>
  </h1>
</div>

<%= render partial: 'layouts/index_functionality', locals: {object: :event_dictionary, per_page: params[:per_page], path: event_dictionary_index_path } %>

<div id="event_dictionary" class="index-content"></div>

app/views/event_dictionary/index.js.erb
$("#event_dictionary").html("<%= escape_javascript(render("event_dictionary")) %>");
$("#ajax_loader").hide();

app/views/event_dictionary/new.html.erb
<% @title = "New Event Dictionary" %>

<%= render 'form' %>

app/views/event_dictionary/show.html.erb
<%=
    render partial: "layouts/show_page_header",
           locals: {
                   model: @event_dictionary,
                   title: "Event Dictionary: #{@event_dictionary.name}",
                   edit_path: edit_event_dictionary_path(@event_dictionary),
                   index_path: event_dictionary_index_path,
                   new_path: new_event_dictionary_path
           }
%>

<div class="row">
  <div class="col-md-6">
    <dl>
      <dt>Name</dt>
      <dd><%= @event_dictionary.name %></dd>

      <dt>Description</dt>
      <dd><%= markdown @event_dictionary.description %></dd>
    </dl>
  </div>

  <div class="col-md-6">
    <dl>
      <dt><%= @event_dictionary.data_dictionary.count %> Data Records</dt>
      <dd>
        <ul>
          <% @event_dictionary.data_dictionary.order(:title).each do |data_record| %>
            <li><%= link_to data_record.title, data_record %></li>
          <% end %>
        </ul>
      </dd>
    </dl>

    <p>Number of existing events: <%= @event_dictionary.events.count %></p>
  </div>
</div>