config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'account(/:auth_token)/profile' => 'account#profile'

  get '/auth/failure', to: 'authentications#failure'
  post '/auth/ldap/callback', to: 'authentications#create'
  get '/auth/ldap', to: 'authentications#passthru'

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login' }, path: ''


  # Resources
  resources :users
  resources :data_dictionary do
    post 'data_attribute_form', :on => :collection
  end
  resources :data_types

  get 'documentations/latest/:type/:id', to: "documentations#latest", as: :latest_documentation
  get 'sources/latest/:type/:id', to: "sources#latest", as: :latest_source

  resources :documentations
  resources :event_dictionary

  post 'events/report', to: "events#report", as: :report

  get 'events/report', to: "events#report"
  get 'events/:name/report/subject/:subject_code/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject/:subject_code', to: "events#report"
  get 'events/:name/report/subject_group/:subject_group_name/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject_group/:subject_group_name', to: "events#report"
  get 'events/:name/report/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report', to: "events#report"

  resources :events do
    get ':name', action: :new, on: :new
  end
  resources :sources
  resources :source_types
  resources :subject_groups
  resources :subjects do
    collection do
      post 'create_list'
      get 'new_list'
    end
  end


  get 'tasci_merger', to: 'tools#tasci_merger', as: :tasci_merger
  post 'tasci_merger', to: 'tools#tasci_merger', as: :merge_tasci

  root 'documentations#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  ##
  # Associations
  has_many :data, autosave: true, dependent: :delete_all
  has_many :quality_flags, :through => :event_quality_flags
  has_many :event_quality_flags
  belongs_to :documentation
  belongs_to :source
  belongs_to :subject

  ##
  # Attributes
  #attr_accessible :documentation_id, :group_label, :name, :notes, :realtime, :source_id, :subject_id, :labtime, :data_list

  ##
  # Callbacks
  before_save :synchronize_times

  ##
  # Concerns
  include Loggable, Deletable, Indexable

  ##
  # Database Settings


  ##
  # Scopes
  scope :search, lambda { |term| search_scope([:name], term) }

  ##
  # Validations
  validate :name_has_to_be_defined_in_dictionary, :time_must_be_defined
  validates_presence_of :name, :subject_id

  ##
  # Variables

  ##
  # Class Methods
  def self.generate_report(name, attrs = {})
    attrs = { ignore_paired: false }.merge attrs
    ed = EventDictionary.find_by_name name
    sql = ed.event_data_query_sql(attrs)

    {sql: sql, result: Event.connection.exec_query(sql)}
  end

  def self.continuous_list(subject, event_record, options = {use_materialized_view: true, refresh: false, recreate: false})

    event_name = event_record.name

    data_query = []
    data_titles = []

    event_record.data_dictionary.each do |dd|
      q = "max( decode( d.title, '#{dd.title}', #{dd.data_type.storage})) #{dd.title}"
      data_titles << dd.title unless data_titles.include? dd.title
      data_query << q unless data_query.include? q
    end

    query = "
      select
        '#{event_name}' event_name,
        max( decode(e.name, '#{event_name}', realtime)) realtime,
        max( decode(e.name, '#{event_name}', labtime_decimal(e.labtime_hour, e.labtime_min, e.labtime_sec))) labtime,
        max( decode(e.name, '#{event_name}', e.labtime_year)) year
        #{(", " + data_query.join(",\n")) unless data_query.empty?}
      from events e
      left join data d on d.event_id = e.id
      left join data_values dv on d.id = dv.datum_id
      where e.subject_id = #{subject.id}
      and e.name = '#{event_name}'
      group by e.subject_id, e.id
    "


    if options[:use_materialized_view]
      materialized_view_name = "mv_#{subject.subject_code}_#{event_name}".upcase
      MY_LOG.info "Using View! #{materialized_view_name}"

      if options[:recreate]
        Event.connection.execute "drop materialized view #{materialized_view_name}", "SQL"
      end

      if options[:refresh]
        Event.connection.execute "BEGIN DBMS_SNAPSHOT.REFRESH( '#{materialized_view_name}','F'); end"
      end

      if Event.connection.exec_query("select mview_name from all_mviews where mview_name = '#{materialized_view_name}'").count == 0
        MY_LOG.info "Creating View! #{materialized_view_name}"
        ddl = "
          create materialized view #{materialized_view_name}
          using index
          refresh on demand complete
          disable query rewrite
          as
          #{query}
        "
        Event.connection.execute(ddl, "SQL")
      end

      res = Event.connection.exec_query("select event_name, realtime, labtime, year, #{data_titles.join(", ")} from #{materialized_view_name} order by labtime")

    else
      query += "order by labtime"
      res = Event.connection.exec_query query
    end

    res.map{|x|
      row_info = {
          realtime: (x["realtime"].getlocal.strftime('%FT%H:%M:%S') if x["realtime"]),
          labtime: x["labtime"],
          year: x["year"],
      }

      data_titles.each do |t|
        row_info[t] = x[t]
      end
      row_info
    }
  end

  def self.interval_list(subject, start_event_record, end_event_record)
    # subject_code, interval_name, labtime, labtime_year, realtime, [data for start event], [data for end event]

    start_event_name = start_event_record.name
    end_event_name = end_event_record.name

    event_dictionaries = {start: start_event_record, end: end_event_record}

    data_query = []
    data_titles = []
    event_dictionaries.values.each do |ed|
      ed.data_dictionary.each do |dd|
        q = "max( decode( d.title, '#{dd.title}', #{dd.data_type.storage})) #{dd.title}"
        data_titles << dd.title unless data_titles.include? dd.title
        data_query << q unless data_query.include? q
      end
    end

    query = "
      select
        max( decode(e.name, '#{start_event_name}', realtime)) start_realtime,
        max( decode(e.name, '#{end_event_name}', realtime)) end_realtime,
        max( decode(e.name, '#{start_event_name}', labtime_decimal(e.labtime_hour, e.labtime_min, e.labtime_sec))) start_labtime,
        max( decode(e.name, '#{end_event_name}', labtime_decimal(e.labtime_hour, e.labtime_min, e.labtime_sec))) end_labtime,
        max( decode(e.name, '#{start_event_name}', e.labtime_year)) start_year,
        max( decode(e.name, '#{end_event_name}', e.labtime_year)) end_year
        #{(", " + data_query.join(",\n")) unless data_query.empty?}
      from events e
      left join data d on d.event_id = e.id
      left join data_values dv on d.id = dv.datum_id
      where e.subject_id = #{subject.id}
      and (
        e.name = '#{start_event_name}' or
        e.name = '#{end_event_name}'
      )
      group by e.subject_id, e.group_label
      having count(e.group_label) > 1
    "

    #MY_LOG.info "VERY IMPORTANTAAKLDFJLKJ!!!!\n\n#{query}\n\n"

    res = Event.connection.exec_query query
    res.map{|x|
      row_info = {
          start_realtime: (x["start_realtime"].getlocal.strftime('%FT%H:%M:%S') if x["start_realtime"]),
          end_realtime: (x["end_realtime"].getlocal.strftime('%FT%H:%M:%S') if x["end_realtime"]),
          start_labtime: x["start_labtime"],
          end_labtime: x["end_labtime"],
          start_year: x["start_year"],
          end_year: x["end_year"]
      }

      data_titles.each do |t|
        row_info[t] = x[t]
      end
      row_info
    }
  end

  def self.direct_create(params)
    ## Differences between normal params and those used for this function:
    ##  event_dictionary (maybe move to outside?) exists in direct create, but not allowed attr normally
    ##  group_label seems to be missing from direct create
    ##  labtime is more flexible: can be sent as decimal or normal.
    ##  quality_flag_id not in accessible attributes yet

    ## :source_id, :subject_id, :labtime, :data_list

    ##

    #MY_LOG.info "dc params: #{params}"

    ## Validate
    [:subject_id, :source_id, :documentation_id, :name, :event_dictionary].each do |param_key|
      raise StandardError, "Missing parameter: #{param_key.to_s} || #{params}" if params[param_key].nil?
    end


    if params[:realtime].present? and params[:labtime].present?
      raise StandardError, "Both labtime and realtime present but do not match." unless params[:realtime] == params[:labtime].to_time
    elsif params[:realtime].present?
      params[:labtime] = Labtime.parse(params[:realtime])
    elsif params[:labtime].present?
      params[:realtime] = params[:labtime].to_time
    else
      raise StandardError, "Cannot create event - neither labtime nor realtime supplied."
    end

    if params[:event_dictionary].data_dictionary.present?
      raise StandardError, "Missing parameter: data_list || #{params}" if params[:data_list].nil?
      unless params[:data_list][:list].map{|dl| dl[:title]}.sort == params[:event_dictionary].data_dictionary.map { |dd| dd.title }.sort
        raise StandardError, "Cannot create event - data values do not match definitions: \nvals:#{params[:data_list][:list].map{|dl| dl[:title]}.sort}\ndefs: #{params[:event_dictionary].data_dictionary.map { |dd| dd.title }.sort}"
      end
    end


    ## Setup Variables
    current_time = Time.zone.now
    conn = self.connection
    ed = params[:event_dictionary]
    event_id = conn.next_sequence_value(self.sequence_name)

    ## Set Values for columns
    event_vals = {
        id: event_id,
        name: params[:name],
        subject_id: params[:subject_id],
        source_id: params[:source_id],
        documentation_id: params[:documentation_id],
        quality_flag_id: params[:quality_flag_id],
        realtime: params[:realtime],
        realtime_offset_sec: params[:realtime_offset_sec],
        labtime_hour: params[:labtime].hour,
        labtime_min: params[:labtime].min,
        labtime_sec: params[:labtime].sec,
        labtime_year: params[:labtime].year,
        labtime_timezone: params[:labtime].time_zone.name,
        created_at: current_time,
        updated_at: current_time,
        notes: params[:notes],
        group_label: params[:group_label],
        deleted: 0
    }
    #MY_LOG.info "EV: #{event_vals}"
    event_binds = self.columns.map {|column| [column, event_vals[column.name.to_sym]]}
    conn.exec_insert "insert into events (#{self.column_names.join(", ")}) values (:#{self.column_names.join(", :")})", "SQL", event_binds

    ed.data_dictionary.each do |dd|
      #LOAD_LOG.info params[:data_list]
      type = dd.data_type.storage.to_sym
      selected_datums = params[:data_list][:list].select{|dv| dv[:title] == dd.title}
      raise StandardError, "Only one value of given title can be provided." unless selected_datums.length < 2

      val = selected_datums.first[:value]
      datum_id = conn.next_sequence_value(Datum.sequence_name)
      data_value_id = conn.next_sequence_value(DataValue.sequence_name)

      d = { id: datum_id, title: dd.title, created_at: current_time, updated_at: current_time, event_id: event_id, deleted: 0 }
      dv = {id: data_value_id, type_flag: type, created_at: current_time, updated_at: current_time, datum_id: datum_id, deleted: 0 }

      # Time value fix - roo does not convert into correct data type
      if type == :time_value
        if  val.class == Fixnum
          t = Time.at(val).getutc
          val = Time.zone.local(1, 1, 1, t.hour, t.min, t.sec)
        elsif val.class == Float
          val = nil
        end
      end

      dv[type] = val

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /documentations
  # GET /documentations.json
  def index
    events_scope = Event.showable
    @events = events_scope.search_by_terms(parse_search_terms(params[:search])).set_order(params[:order], "title asc").page_per(params) #.page(params[:page] ? params[:page] : 1).per(params[:per_page] == "all" ? nil : params[:per_page])
  end

  # GET /events/report/name/subject_code/subject_group_name/ignore_paired
  # GET /events/report/name.json
  def report
    params.keep_if {|k, v| v.present? }
    @report = Event.generate_report(params[:name], {subject_group_name: params[:subject_group_name], subject_code: params[:subject_code], ignore_paired: params[:ignore_paired]})
  end

  # GET /documentations/1
  # GET /documentations/1.json
  def show
  end

  # GET /documentations/new
  def new
    @event = Event.new(name: params[:name])
  end

  # GET /documentations/1/edit
  def edit
  end

  # POST /documentations
  # POST /documentations.json
  def create

    @event = Event.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @documentation }
      else
        format.html { render action: 'new' }
        format.json { render json: @documentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentations/1
  # PATCH/PUT /documentations/1.json
  #def update
  #  respond_to do |format|
  #    if @documentation.logged_update(documentation_params)
  #      format.html { redirect_to @documentation, notice: 'Documentation was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: 'edit' }
  #      format.json { render json: @documentation.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /documentations/1
  # DELETE /documentations/1.json
  #def destroy
  #  @documentation.destroy
  #  respond_to do |format|
  #    format.html { redirect_to documentations_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.current.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def documentation_params
    params.require(:documentation).permit(:name, :labtime_year, :labtime_hour, :labtime_min, :labtime_sec, :realtime, :subject_id, data_list: [ :clear_all, list: [:title, :value, :notes]] )
  end
end

app/views/events/_post_sleep_questionnaire_form.html.erb
<div class="page-header">
  <h1>New Form <small>Post-Sleep Questionnaire</small></h1>
</div>
<div id="event_form">
  <%= form_for @event, html: {role: 'form'} do |f| %>
    <%= display_errors @event %>

    <%= f.hidden_field :name, value: @event.name %>
    <div class="row">
      <div class="col-md-6">
        <fieldset>
          <div class="form-group">
            <label for="subject_code" class="control-label">Subject code</label>
            <input type="text" name="subject_code" id="subject_code" placeholder="Subject Code" class="form-control">
          </div>

          <div class="form-group">
            <label for="event[labtime]" class="control-label">Subject code</label>
            <input type="text" name="subject_code" id="subject_code" placeholder="Subject Code" class="form-control">
          </div>

        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset>
            <% @event.event_dictionary.data_dictionary.each do |dd_record| %>
              <div class="form-group">
                <input type="hidden" name="event[data_list][title]" value="<%= dd_record.title %>">
                <label for="event[data_list][value]" class="control-label"><%= dd_record.title.titleize %></label>
                <input type="text" class="form-control" class="form-control" name="event[data_list][value]">
              </div>
            <% end %>
        </fieldset>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit "Create #{@event.name.titleize}", class: 'btn btn-primary' %>
      <%= cancel %>
    </div>
<% end %>
</div>

app/views/events/edit.html.erb
<% @title = "Edit Documentation: #{@documentation.title}" %>

<%= render 'form' %>

app/views/events/index.html.erb
<% @title = 'Documentations' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Documentation", new_documentation_path, class: 'btn btn-mini btn-primary' %>
  </h1>
</div>

<%= render partial: 'layouts/index_functionality', locals: {object: :documentations, per_page: params[:per_page], path: documentations_path } %>


<div id="documentations" class="index-content"></div>

app/views/events/index.js.erb
$("#documentations").html("<%= escape_javascript(render("documentations")) %>");
$("#ajax_loader").hide();

app/views/events/new.html.erb
<% @title = "New #{@event.name.titleize}" %>

<%= render partial: "#{@event.name}_form" %>

app/views/events/report.html.erb
<% @title = "Report for #{params[:name]}" %>
<div class="page-header">
  <h1>
    <%= @title %>
  </h1>
</div>

<div id="report-generator" class="well">
  <%= form_tag report_path do %>
    <div class="row">
      <div class="col-md-10">
        <div class="row">
          <div class="form-group col-md-4">
            <%= select_tag :subject_code, options_for_select([nil]+Subject.current.map(&:subject_code), params[:subject_code]), {rel: 'chosen', class: 'form-control', data: {placeholder: "Select subject..."}} %>
          </div>
          <div class="form-group col-md-4">
            <%= select_tag :subject_group_name, options_for_select([nil]+SubjectGroup.current.map(&:name), params[:subject_group_name]), {rel: 'chosen', class: 'form-control', data: {placeholder: "Select subject group..."}} %>
          </div>
          <div class="form-group col-md-4">
            <%= select_tag :name, options_for_select([nil]+EventDictionary.current.map(&:name), params[:name]), {rel: 'chosen', class: 'form-control', data: {placeholder: "Select event name..."}} %>
          </div>
        </div>
        <div class="row selected-cols">
          <div class="form-group col-md-12">
            <%= select_tag :selected_columns, options_for_select(@report[:result].columns, params[:selected_columns]), {multiple:true, rel: 'chosen', class: 'form-control', data: {placeholder: "Select columns to display..."}} %>
          </div>
        </div>

      </div>
      <div class="form-group col-md-2">
        <button type="submit" class="btn btn-primary btn-lg btn-block">Update</button>
      </div>
    </div>

<% end %>
</div>

<div id="report">
  <table class="table table-striped table-bordered table-condensed datatable">
    <thead>
    <tr>
      <% @report[:result].columns.each do |colname| %>
        <% if params[:selected_columns].blank? or  params[:selected_columns].include? colname %>
          <th><%= colname %></th>
        <% end %>
      <% end %>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @report[:result].each do |r| %>
      <tr>
        <% r.each do |colname, value|%>
          <% if params[:selected_columns].blank? or  params[:selected_columns].include? colname %>
            <td><%= value =~ /^[-+]?[0-9]*\.?[0-9]+$/ ? value.round(3) : value %></td>
          <% end %>
        <% end %>
        <td>
          <% if r["event_id"] %>
            <%= link_to "documenatation", latest_documentation_path(type: :event, id: r["event_id"]), class: "btn btn-xs btn-default" %>
            <%= link_to "source", latest_source_path(type: :event, id: r["event_id"]), class: "btn btn-xs btn-default" %>
          <% end %>
        </td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

<h3>SQL:</h3>
<pre><%= @report[:sql] %></pre>