config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'account(/:auth_token)/profile' => 'account#profile'

  get '/auth/failure', to: 'authentications#failure'
  post '/auth/ldap/callback', to: 'authentications#create'
  get '/auth/ldap', to: 'authentications#passthru'

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login' }, path: ''


  # Resources
  resources :users
  resources :data_dictionary do
    post 'data_attribute_form', :on => :collection
  end
  resources :data_types

  get 'documentations/latest/:type/:id', to: "documentations#latest", as: :latest_documentation
  get 'sources/latest/:type/:id', to: "sources#latest", as: :latest_source

  resources :documentations
  resources :event_dictionary

  post 'events/report', to: "events#report", as: :report

  get 'events/report', to: "events#report"
  get 'events/:name/report/subject/:subject_code/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject/:subject_code', to: "events#report"
  get 'events/:name/report/subject_group/:subject_group_name/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject_group/:subject_group_name', to: "events#report"
  get 'events/:name/report/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report', to: "events#report"

  resources :events do
    get ':name', action: :new, on: :new
  end
  resources :sources
  resources :source_types
  resources :subject_groups
  resources :subjects do
    collection do
      post 'create_list'
      get 'new_list'
    end
  end


  get 'tasci_merger', to: 'tools#tasci_merger', as: :tasci_merger
  post 'tasci_merger', to: 'tools#tasci_merger', as: :merge_tasci

  root 'documentations#index'
end

app/models/data_dictionary.rb
class DataDictionary < ActiveRecord::Base
  ##
  # Associations
  belongs_to :min_data_value, :class_name => "DataValue", :foreign_key => :min_value_id, :autosave => true
  belongs_to :max_data_value, :class_name => "DataValue", :foreign_key => :max_value_id, :autosave => true
  has_many :allowed_data_values, :class_name => "DataValue", :through => :data_dictionary_data_values, :source => :data_value, :autosave => true
  has_many :data_dictionary_data_values
  has_many :event_dictionary, :through => :event_dictionary_data_fields
  has_many :event_dictionary_data_fields
  belongs_to :data_type
  #has_many :data, :foreign_key => :title, :primary_key => :title

  ##
  # Attributes
  #attr_accessible :data_type_id, :description, :max_length, :max_value, :max_value_inclusive, :min_length, :min_value, :min_value_inclusive, :multivalue, :title, :unit, :allowed_values

  ##
  # Callbacks

  ##
  # Concerns
  include Indexable, Loggable, Deletable

  ##
  # Scopes
  scope :search, lambda { |term| search_scope([:title, :description, :unit], term) }

  ##
  # Validations
  validates_presence_of :title
  validates_uniqueness_of :title

  ##
  # Class Methods

  ##
  # Instance Methods

  def allowed_values=(val_array)
    allowed_data_values.clear

    val_array.each do |val|
      if val.present?
        dv = allowed_data_values.build
        dv.force_type!(self.data_type)
        dv.value = val
      end
    end
  end

  def allowed_values
    allowed_values? ? allowed_data_values.collect {|dv| dv.value} : nil
  end

  def max_value=(val)
    if max_data_value.present?
      max_data_value.value = val
    else
      mv = build_max_data_value
      mv.data_dictionary_as_max_value = self
      mv.value = val
    end
  end

  def min_value=(val)
    if min_data_value
      min_data_value.value = val
    else
      mv = build_min_data_value
      mv.data_dictionary_as_min_value = self
      mv.value = val
    end
  end

  def max_value
    max_value? ? max_data_value.value : nil
  end

  def min_value
    min_value? ? min_data_value.value : nil
  end

  def min_value?
    data_type && data_type.range? && !min_data_value.nil?
  end

  def max_value?
    data_type && data_type.range? && !max_data_value.nil?
  end

  def allowed_values?
    data_type && data_type.values? && !allowed_data_values.empty? && !allowed_data_values.nil?
  end

  def min_length?
    !min_length.nil? && data_types.length?
  end

  def max_length?
    !max_length.nil? && data_types.length?
  end

  private

end

app/controllers/data_dictionary_controller.rb
class DataDictionaryController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_data_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /data_dictionary
  # GET /data_dictionary.json
  def index
    data_dictionary_scope = DataDictionary.current
    @data_dictionary = data_dictionary_scope.search_by_terms(parse_search_terms(params[:search])).set_order(params[:order], "title asc").page_per(params) #.page(params[:page] ? params[:page] : 1).per(params[:per_page] == "all" ? nil : params[:per_page])
  end

  # GET /data_dictionary/1
  # GET /data_dictionary/1.json
  def show
  end

  # GET /data_dictionary/new
  def new
    @data_dictionary = DataDictionary.new
  end

  # GET /data_dictionary/1/edit
  def edit
  end

  # POST /data_dictionary
  # POST /data_dictionary.json
  def create
    @data_dictionary = DataDictionary.logged_new(data_dictionary_params, current_user)

    respond_to do |format|
      if @data_dictionary.save
        format.html { redirect_to @data_dictionary, notice: 'DataDictionary was successfully created.' }
        format.json { render action: 'show', status: :created, location: @data_dictionary }
      else
        format.html { render action: 'new' }
        format.json { render json: @data_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_dictionary/1
  # PATCH/PUT /data_dictionary/1.json
  def update
    respond_to do |format|
      if @data_dictionary.logged_update(data_dictionary_params)
        format.html { redirect_to @data_dictionary, notice: 'DataDictionary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @data_dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_dictionary/1
  # DELETE /data_dictionary/1.json
  def destroy
    @data_dictionary.destroy
    respond_to do |format|
      format.html { redirect_to data_dictionary_index_url }
      format.json { head :no_content }
    end
  end


  def data_attribute_form
    data_dictionary = params[:data_dictionary_id].empty? ? DataDictionary.new : DataDictionary.find(params[:data_dictionary_id])

    data_dictionary.min_data_value = DataValue.new if data_dictionary.min_data_value.nil?
    data_dictionary.max_data_value = DataValue.new if data_dictionary.max_data_value.nil?
    data_dictionary.allowed_data_values.build #if data_dictionary.allowed_values.blank? (might be needed for blank template)

    render :partial => "data_attributes", :locals => {data_type: DataType.find(params[:data_type_id]), data_dictionary: data_dictionary }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_data_dictionary
    @data_dictionary = DataDictionary.current.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def data_dictionary_params
    params.require(:data_dictionary).permit(:title, :description, :data_type_id, :data_unit_id, :min_value, :min_value_inclusive, :max_value, :max_value_inclusive, :multivalue, :min_length, :max_length_integer, :unit, allowed_values: [])
  end
end

app/views/data_dictionary/_data_attributes.html.erb
<%=
    # Params:
    # Data Dictionary
    # Data Type
%>

<%= fields_for data_dictionary do |f| %>
  <% if data_type.storage == "num_value" || data_type.range? || data_type.length? %>
      <% if data_type.multiple? %>
        <div id="multiple_field" class="attribute_field">
          <div class="form-group">
            <%= f.label :multivalue, "Can data have more than one value?", class: 'control-label' %>
            <div class="radio">
              <label>
                <%= f.radio_button :multivalue, 0, checked: true %> No
              </label>
            </div>
            <div class="radio">
              <label>
                <%= f.radio_button :multivalue, 1 %> Yes
              </label>
            </div>
          </div>
        </div>
      <% end %>

      <% if data_type.storage == "num_value" %>
        <div id="unit_field" class="attribute_field">
          <div class="form-group">
            <%= f.label :unit, nil, class: 'control-label' %>
            <%= f.text_field :unit, class: 'form-control' %>
          </div>
        </div>
      <% end %>

      <% if data_type.range? %>
        <div id="range_fields" class="attribute_field">
          <div class="form-group">
            <%= f.label :min_value, "Min Value", class: 'control-label' %>
            <div class="controls">
              <%= value_field(f, data_type, data_dictionary.min_value, "min_value") %>
              <div class="nested_checkbox">
                <%= f.check_box :min_value_inclusive %>
                <%= f.label :min_value_inclusive, "Inclusive?" %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :max_value, "Max Value ", class: 'control-label' %>
            <div class="controls">
              <%= value_field(f, data_type, data_dictionary.max_value, "max_value") %>

              <div class="nested_checkbox">
                <%= f.check_box :max_value_inclusive %>
                <%= f.label :max_value_inclusive, "Inclusive?"%>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% if data_type.length? %>
        <div id="length_fields" class="attribute_field">
          <div class="form-group">
            <%= f.label :min_length, nil, class: 'control-label' %>
            <%= f.number_field :min_length, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :max_length, nil, class: 'control-label' %>
            <%= f.number_field :max_length, class: 'form-control' %>
          </div>
        </div>
      <% end %>
  <% end %>

  <% if data_type.values? %>
    <fieldset>
      <legend>Allowed Values</legend>
      <div id="value_fields" class="attribute_field">
        <ol>
          <% data_dictionary.allowed_data_values.each do |allowed_value| %>
            <li>
              <%= f.fields_for "allowed_values" do |val_f| %>
                <%= value_field(val_f, data_type, allowed_value.value, "", false, true) %>
              <% end %>
              <%= link_to 'Remove', '#', class: 'btn btn-mini btn-danger remove' %>
            </li>
          <% end %>
        </ol>
        <%= link_to "Add Another Allowed Value", "#", class: 'btn btn-mini', id: "add_value_field" %>
      </div>
    </fieldset>
  <% end %>
<% end %>

app/views/data_dictionary/_data_dictionary.html.erb
<p class='text-info object-info'><%= page_entries_info @data_dictionary %></p>
<table class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
      <th><%= sort_field_helper(params[:order], 'title', 'Title') %></th>
      <th><%= sort_field_helper(params[:order], 'description', 'Description') %></th>
      <th>Data Type</th>
      <th><%= sort_field_helper(params[:order], 'unit', 'Unit') %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <% @data_dictionary.each do |data_dictionary| %>
    <tr>
      <td><%= link_to data_dictionary.title, data_dictionary %></td>
      <td><%= truncate(data_dictionary.description, length: 100) %></td>
      <td><%= link_to data_dictionary.data_type.name, data_dictionary.data_type if data_dictionary.data_type %></td>
      <td><%= data_dictionary.unit %></td>
      <td>
        <%= render partial: "layouts/index_actions", locals: {object: data_dictionary, edit_path: edit_data_dictionary_path(data_dictionary) } %>
      </td>
    </tr>
  <% end %>
</table>

<div class="center"><%= paginate @data_dictionary %></div>

app/views/data_dictionary/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<%= form_for @data_dictionary, html: { role: 'form', id: "data_dictionary", data: {data_dictionary_id: @data_dictionary.id, form_path: data_attribute_form_data_dictionary_index_path}  } do |f| %>
    <%= display_errors @data_dictionary %>
    <div class="row">

      <div class="col-md-6">
        <fieldset>
          <legend>Main Information</legend>

          <div class="form-group">
            <%= f.label :title, nil, class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control   ' %>
          </div>

          <div class="form-group">
            <%= f.label :description, nil, class: 'control-label' %>
            <%= f.text_area :description, rows: 7, class: 'form-control description' %>
          </div>
        </fieldset>
      </div>
      <div class="col-md-6">
        <fieldset>
          <legend>Data Attributes</legend>
          <div class="form-group">
            <%= f.label :data_type_id, nil, class: 'control-label' %>
            <%= f.select :data_type_id, [['---', nil]] + DataType.current.collect{|d| [d.name, d.id]}, {}, {rel: :chosen, class: 'form-control', data: {placeholder: "Select the data type of this variable..."}} %>
          </div>
          <div id="data_attributes"></div>
        </fieldset>
      </div>
    </div>
    <div class="form-actions">
        <%= f.submit "Create Data Dictionary entry", class: 'btn btn-primary' %>
        <%= cancel %>
    </div>
<% end %>

app/views/data_dictionary/edit.html.erb
<% @title = "Edit Data Dictionary: #{@data_dictionary.title}" %>

<%= render 'form' %>

app/views/data_dictionary/index.html.erb
<% @title = 'Data Dictionaries' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Data Dictionary entry", new_data_dictionary_path, class: 'btn btn-mini btn-primary' %>
  </h1>
</div>

<%= render partial: 'layouts/index_functionality', locals: {object: :data_dictionary, per_page: params[:per_page], path: data_dictionary_index_path } %>

<div id="data_dictionary" class="index-content"></div>

app/views/data_dictionary/index.js.erb
$("#data_dictionary").html("<%= escape_javascript(render("data_dictionary")) %>");
$("#ajax_loader").hide();

app/views/data_dictionary/new.html.erb
<% @title = "New Data Dictionary" %>

<%= render 'form' %>

app/views/data_dictionary/show.html.erb
<%=
  render partial: "layouts/show_page_header",
         locals: {
              model: @data_dictionary,
              title: "Data Dictionary: #{@data_dictionary.title}",
              edit_path: edit_data_dictionary_path(@data_dictionary),
              index_path: data_dictionary_index_path,
              new_path: new_data_dictionary_path
         }
%>

<dl class="dl-horizontal">
  <dt>Title</dt>
  <dd><%= @data_dictionary.title %></dd>

  <dt>Description</dt>
  <dd><%= markdown @data_dictionary.description %></dd>

  <dt>Data Type</dt>
  <dd><%= link_to @data_dictionary.data_type.name, @data_dictionary.data_type if @data_dictionary.data_type %></dd>

  <% if %w(integer_type numeric_type).include? @data_dictionary.data_type.name %>
    <dt>Unit</dt>
    <dd><%= @data_dictionary.unit %></dd>
  <% end %>

  <% if @data_dictionary.data_type.range? %>
    <dt>Min Value</dt>
    <dd id="min_val"><%= @data_dictionary.min_value %><span><%= " (inclusive)" if @data_dictionary.min_value_inclusive %></span></dd>

    <dt>Max Value</dt>
    <dd id="max_val"><%= @data_dictionary.max_value %><span><%= " (inclusive)" if @data_dictionary.min_value_inclusive %></span></dd>
  <% end %>

  <% if @data_dictionary.data_type.multiple? %>
    <dt>Multiple Values Allowed</dt>
    <dd><%= @data_dictionary.multivalue %></dd>
  <% end %>

  <% if @data_dictionary.data_type.length? %>
    <dt>Min Length</dt>
    <dd id="min_length"><%= @data_dictionary.min_length %></dd>

    <dt>Max Length</dt>
    <dd id="max_length"><%= @data_dictionary.max_length %></dd>
  <% end %>

  <% if @data_dictionary.data_type.values? and @data_dictionary.allowed_values? %>
    <dt>Allowed Values</dt>
    <dd id="allowed_values">
      <ul>
        <% @data_dictionary.allowed_values.each do |val| %>
          <li><%= val %></li>
        <% end %>
      </ul>
    </dd>
  <% end %>
</dl>