config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'account(/:auth_token)/profile' => 'account#profile'

  get '/auth/failure', to: 'authentications#failure'
  post '/auth/ldap/callback', to: 'authentications#create'
  get '/auth/ldap', to: 'authentications#passthru'

  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login' }, path: ''


  # Resources
  resources :users
  resources :data_dictionary do
    post 'data_attribute_form', :on => :collection
  end
  resources :data_types

  get 'documentations/latest/:type/:id', to: "documentations#latest", as: :latest_documentation
  get 'sources/latest/:type/:id', to: "sources#latest", as: :latest_source

  resources :documentations
  resources :event_dictionary

  post 'events/report', to: "events#report", as: :report

  get 'events/report', to: "events#report"
  get 'events/:name/report/subject/:subject_code/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject/:subject_code', to: "events#report"
  get 'events/:name/report/subject_group/:subject_group_name/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report/subject_group/:subject_group_name', to: "events#report"
  get 'events/:name/report/ignore_paired', to: "events#report", defaults: {ignore_paired: 1}
  get 'events/:name/report', to: "events#report"

  resources :events do
    get ':name', action: :new, on: :new
  end
  resources :sources
  resources :source_types
  resources :subject_groups
  resources :subjects do
    collection do
      post 'create_list'
      get 'new_list'
    end
  end


  get 'tasci_merger', to: 'tools#tasci_merger', as: :tasci_merger
  post 'tasci_merger', to: 'tools#tasci_merger', as: :merge_tasci

  root 'documentations#index'
end

app/models/irb.rb
class Irb < ActiveRecord::Base
  ##
  # Associations
  has_many :subjects, :through => :subjects_irbs
  has_many :subjects_irbs

  ##
  # Attributes
  # attr_accessible :number, :title

  ##
  # Callbacks

  ##
  # Concerns
  include Loggable, Deletable

  ##
  # Database Settings

  ##
  # Scopes

  ##
  # Validations
  validates_presence_of :irb_number, :title
  validates_uniqueness_of :irb_number

  ##
  # Class Methods

  ##
  # Instance Methods

  private
end

app/models/subject_group.rb
class SubjectGroup < ActiveRecord::Base
  ##
  # Associations
  has_many :subjects, :through => :subjects_subject_groups
  has_many :subjects_subject_groups

  ##
  # Attributes
  # attr_accessible :description, :name, :subject_ids

  ##
  # Callbacks

  ##
  # Concerns
  include Loggable, Indexable, Deletable

  ##
  # Database Settings

  ##
  # Scopes
  scope :search, lambda { |term| search_scope([:name, :description], term) }

  ##
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name, scope: :deleted

  ##
  # Class Methods

  ##
  # Instance Methods
end

app/controllers/subject_groups_controller.rb
class SubjectGroupsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_subject_group, only: [:show, :edit, :update, :destroy]

  # GET /subject_groups
  # GET /subject_groups.json
  def index
    subject_groups_scope = SubjectGroup.current
    @subject_groups = subject_groups_scope.search_by_terms(parse_search_terms(params[:search])).set_order(params[:order], "created_at desc").page_per(params)
  end

  # GET /subject_groups/1
  # GET /subject_groups/1.json
  def show
  end

  # GET /subject_groups/new
  # GET /subject_groups/new.json
  def new
    @subject_group = SubjectGroup.new
  end

  # GET /subject_groups/1/edit
  def edit
  end

  # POST /subject_groups
  # POST /subject_groups.json
  def create
    @subject_group = SubjectGroup.logged_new(subject_group_params, current_user)

    respond_to do |format|
      if @subject_group.save
        format.html { redirect_to @subject_group, notice: 'SubjectGroup was successfully created.' }
        format.json { render json: @subject_group, status: :created, location: @subject_group }
      else
        format.html { render action: "new" }
        format.json { render json: @subject_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subject_groups/1
  # PUT /subject_groups/1.json
  def update
    @subject_group = SubjectGroup.current.find(params[:id])

    respond_to do |format|
      if @subject_group.logged_update(subject_group_params, current_user)
        format.html { redirect_to @subject_group, notice: 'SubjectGroup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_groups/1
  # DELETE /subject_groups/1.json
  def destroy
    @subject_group.destroy

    respond_to do |format|
      format.html { redirect_to subject_groups_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_subject_group
    @subject_group = SubjectGroup.current.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def subject_group_params
    params.require(:subject_group).permit(:name, :description, subject_ids: [])
  end
end

app/views/subject_groups/_form.html.erb
<div class="page-header">
  <h1><%= @title %></h1>
</div>

<div id="subject_group_form">
  <div class="row">
    <div class="col-md-6">
      <%= form_for @subject_group, html: { role: 'form' }  do |f| %>
          <%= display_errors @subject_group %>
          <fieldset>
            <legend>Main Information</legend>
            <div class="form-group">
              <%= f.label :name, nil%>
              <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :description, nil%>
              <%= f.text_area :description, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :subject_ids, "Subjects" %><br/>
              <%= f.collection_select :subject_ids, Subject.current.order(:subject_code), :id, :subject_code, {}, {multiple:true, rel: 'chosen', class: 'form-control'} %>
            </div>
          </fieldset>
          <div class="form-actions">
            <%= f.submit nil, class: 'btn btn-primary' %>
            <%= cancel %>
          </div>
      <% end %>
    </div>
    <div class="col-md-6" id="subject_addition_tools">
      <%= form_tag subjects_path, id: 'merge_subject_groups' do  %>
        <%= hidden_field_tag :per_page, "all"  %>
        <fieldset>
          <legend>Merge in other subject groups<span><%= submit_tag "Merge", class: 'btn btn-warning btn-xs pull-right' %></span></legend>
          <div class="form-group">
            <%= label_tag :subject_group_ids, nil, class: 'sr-only' %>
            <%= select_tag :subject_group_ids, options_from_collection_for_select(SubjectGroup.current.order(:name), :id, :name), {multiple:true, rel: 'chosen', class: 'form-control', data: {placeholder: 'Select Subject Groups'}} %>

          </div>
        </fieldset>
      <% end %>
      <%= form_tag subjects_path, id: 'add_bulk_subjects' do %>
        <%= hidden_field_tag :per_page, "all"  %>
        <fieldset>
          <legend>Bulk-add subjects <span><%= submit_tag "Add", class: 'btn btn-warning pull-right btn-xs' %></span></legend>
          <div class="form-group">
            <%= label_tag :subject_codes, nil, class: 'sr-only' %>
            <%= text_area_tag :subject_codes, nil, class: 'form-control', placeholder: 'Enter comma-separated subject codes' %>
          </div>
</fieldset>
      <% end %>
    </div>
  </div>


</div>

app/views/subject_groups/_subject_groups.html.erb
<p class='text-info object-info'><%= page_entries_info @subject_groups %></p>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= sort_field_helper(params[:order], 'name', 'Name') %></th>
      <th><%= sort_field_helper(params[:order], 'description', 'Description') %></th>
      <th>Member Subjects</th>
      <th><%= sort_field_helper(params[:order], 'created_at', 'Created At') %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>


  <tbody>
    <% @subject_groups.each do |subject_group| %>
      <tr>
        <td><%= link_to subject_group.name, subject_group %></td>
        <td><%= truncate(subject_group.description, length: 100) %></td>
        <td>
          <p>
            <% subject_group.subjects.each do |subject| %>
              <%= link_to subject.subject_code, nil %>
              <span>&nbsp;</span>
            <% end %>
          </p>
          <p class="text-muted">Count: <%= subject_group.subjects.count %></p>
        </td>
        <td><%= simple_date(subject_group.created_at) %></td>

        <td>
          <%= render partial: 'layouts/index_actions', locals: {object: subject_group, edit_path: edit_subject_group_path(subject_group)} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center navigation"><%= paginate @subject_groups %></div>

app/views/subject_groups/edit.html.erb
<% @title = "Edit Subject: #{@subject_group.name}" %>

<%= render 'form' %>

app/views/subject_groups/index.html.erb
<% @title = 'Subject Groups' %>
<div class="page-header">
  <h1>
    <%= @title %>
    <%= link_to "Create Subject Group", new_subject_group_path, class: 'btn btn-primary pull-right' %>
  </h1>
</div>

<%= render partial: 'layouts/index_functionality', locals: {object: :subject_groups, per_page: params[:per_page], path: subject_groups_path  } %>


<div id="subject_groups" class="index-content"></div>

app/views/subject_groups/index.js.erb
$("#subject_groups").html("<%= escape_javascript(render("subject_groups")) %>");
$("#ajax_loader").hide();

app/views/subject_groups/new.html.erb
<% @title = "New Subject Group" %>

<%= render 'form' %>

app/views/subject_groups/show.html.erb
<%=
    render partial: "layouts/show_page_header",
           locals: {
                   model: @subject_group,
                   title: "Subject Group: #{@subject_group.name}",
                   edit_path: edit_subject_group_path(@subject_group),
                   index_path: subject_groups_path,
                   new_path: new_subject_group_path
           }
%>

<div id="main_info">
  <dl class="dl-horizontal">
    <dt>Name</dt>
    <dd><%= @subject_group.name %></dd>

    <dt>Description</dt>
    <dd><%= @subject_group.description %></dd>

    <dt>Subjects</dt>
    <dd>
      <ul class="inline">
        <% @subject_group.subjects.each do |subject| %>
          <li><%= link_to subject.subject_code, nil %></li>
        <% end %>
      </ul>
    </dd>
  </dl>
</div>